-- Run this in Supabase SQL Editor to create the handles table

create table public.handles (
  id bigint generated by default as identity primary key,
  name text not null,
  audience text default '',
  platform text not null check (platform in ('TikTok', 'Instagram', 'Both')),
  tiktok_handle text,
  instagram_handle text,
  edit_token text unique not null,
  created_at timestamptz default now()
);

-- Enable Row Level Security
alter table public.handles enable row level security;

-- Anyone can insert (submit a form)
create policy "Anyone can submit"
  on public.handles for insert
  with check (true);

-- Anyone can view all entries (for the admin/community view)
create policy "Anyone can view"
  on public.handles for select
  using (true);

-- Anyone can update their own entry using the edit token
create policy "Anyone can update own entry"
  on public.handles for update
  using (true)
  with check (true);

-- Anyone can delete their own entry using the edit token
create policy "Anyone can delete own entry"
  on public.handles for delete
  using (true);

-- Optional: index on edit_token for fast lookups
create index on public.handles (edit_token);
